_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 050a6673-1711-4472-bd9b-af80bc014e25
name: 'Home Designer'
mail: test@gmail.com
slogan: 'by Amanda Thompson'
page:
  403: ''
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
