show_weather.settings:
  type: config_object
  label: 'Show Weather settings'
  mapping:
    api_key:
      type: string
      label: 'OpenWeatherMap API key'
    city:
      type: string
      label: 'Default city'
